### ISSUE TITLE
Question: on how to compute conditional mutual information against a set of features

### ISSUE THREAD

**Issue by ivan-marroquin** [gregversteeg/NPEET#15]
Hi there!

Thanks for making this package available to us. I was wondering how could be possible to compute a conditional mutual information of features X and Y condition to a set of features S (note that the set can have one or more features). 

If it is possible, how would you proceed? Can this workflow be applied to continuous data (all features) and discrete data (all features).

Many thanks for your help,

Ivan

**Comment by gregversteeg** [comment]
You can do "cmi(x, y, S)" if everything is continuous. If any of them are mixed continuous / discrete, we can't do that. I saw a paper about [mixed discrete continuous entropy](http://papers.nips.cc/paper/7180-estimating-mutual-information-for-discrete-continuous-mixtures)

**Comment by ivan-marroquin** [comment]
Hi @gregversteeg ,

Thanks for the suggestion. In case everything is discrete, then I can use "cmidd(x, y, S)". Also, thanks for sharing the reference.

Ivan
