### ISSUE TITLE
Unexpected scaling of mutual information with variance

### ISSUE THREAD

**Issue by aleksejs-fomins** [gregversteeg/NPEET#19]
Dear Greg,

I am getting strange behaviour in estimated mutual information. I want to check how much the mutual information I(aX, Y) depends on a positive scalar factor a. To the best of my knowledge, analytically mutual information should be completely independent of the scalar factor. However, when I try to estimate it with NPEET, the mutual information is decreasing significantly with increasing alpha. Can you comment on this please?

Here is the minimal example:

```
from npeet.entropy_estimators import mi
x = np.random.uniform(0,1,(1000,1))
y = np.random.uniform(0,1,(1000,1))
z = 0.5*x + 0.5*y
alphaLst = np.arange(1, 100)

miLst = [mi(a*x, z) for a in alphaLst]

plt.figure()
plt.plot(alphaLst, miLst)
plt.show()
```

**Comment by gregversteeg** [comment]
Sorry for the slow response, this is expected (though not desirable!) behavior for the estimator. The estimator is constructed using a nearest neighbors graph in the joint x,z space. You can imagine that if you scale x, the nearest neighbors might change. If the scales are very incomparable (like "a" is very large), the nearest neighbor will be a point with a similar value of x, even though the z values are very dissimilar. That means we are not finding related pairs in the nearest neighbor graph.  As a rule of thumb, it is better to set the length scale for all the variables to be directly comparable.

**Comment by aleksejs-fomins** [comment]
Great, thanks for your reply. I just wanted to make sure I was understanding the situation correctly. I'll do as you suggest.
