### ISSUE TITLE
How compute conditioned entropy

### ISSUE THREAD

**Issue by ivan-marroquin** [gregversteeg/NPEET#28]
Hi,

Thanks for this excellent package!

How do you compute the conditioned entropy? For instance, given the conditioned mutual information I(X,Y|Z), the conditioned entropy that I want to compute are H(X|Z) and H(Y|Z).

Many thanks for your advice,

Ivan

**Comment by gregversteeg** [comment]
We do it in the most naive way - for every value of z, estimate entropy. Then average them. This only works if you have good enough data!
