### ISSUE TITLE
entropy value is negative

### ISSUE THREAD

**Issue by pittmiqi** [gregversteeg/NPEET#6]
Hello, 
 I am using your package to calculate the entropy for a continuous variable, however the entropy value I got is a negative number. Also I tried centropy(x,x), conditional entropy on itself. The result supposes to be zero. However, the results returned sometimes a positive or negative number, but not close to zero. Could you help me explain the issue?  For discrete case, the result looks fine. 
Thanks

**Comment by gregversteeg** [comment]
For continuous variables, this package is calculating the differential entropy. Unfortunately, the differential entropy can be negative, making interpretation more difficult than in the discrete case. See chapter 8 of Cover and Thomas, for example, for a discussion of how to interpret negative differential entropies. (Consider, for instance, the differential entropy for a Gaussian which is proportional to log variance. If the variance is small, you get a negative number.)
